### ISSUE TITLE
Calcular Métricas por Programa y Año.

### ISSUE THREAD

**Issue by Alejost7** [300CIS017-Object-Oriented-Programming/proyecto-3-pinche_trump#13]
## Tareas: 
- Implementar funciones para calcular cada métrica 
- Integrar estas funciones para procesar los datos de manera eficiente.

**Comment by jorluos** [comment]
GRACIAS A LA FUNCION CACHE DE PANDAS EL PROCESAMIENTO DE DATOS SOLO SE DEBE HJACER UNA VEZ LO QUE PERMITE QUE ESTE MISMO SEA MAS EFICIENTE

**Comment by samuelbonillaf** [comment]
Efectivamente quedo chimba
