### ISSUE TITLE
Permitir Descarga de Resultados en Formatos XLSX, JSON y CSV.

### ISSUE THREAD

**Issue by Alejost7** [300CIS017-Object-Oriented-Programming/proyecto-3-pinche_trump#15]
### Tareas: 
- Utilizar Pandas para exportar los datos en los formatos especificados. 
- Añadir botones en la interfaz de Streamlit para la descarga

**Comment by samuelbonillaf** [comment]
Ya esta funciona sin problemas

**Comment by samuelbonillaf** [comment]
El excel esta dando problemas

**Comment by samuelbonillaf** [comment]
Ya esta JOYA 👌💎
