### ISSUE TITLE
Aplicar Principios GRASP en la Estructura de Clases.

### ISSUE THREAD

**Issue by Alejost7** [300CIS017-Object-Oriented-Programming/proyecto-3-pinche_trump#21]
### Tareas: 
- Revisar y refactorizar las clases existentes según los principios GRASP.
- documentar los cambios realizados.

**Comment by samuelbonillaf** [comment]
Mas o menos, no separamos la logica del front a la del back end pero ya es tarde `(*>﹏<*)′
