### ISSUE TITLE
Estilo y Formato del Código

### ISSUE THREAD

**Issue by Alejost7** [300CIS017-Object-Oriented-Programming/proyecto-3-pinche_trump#22]
### Tareas:
- Configurar un linter en el proyecto
- Asegurarse de que el código cumpla con los estándares del linter

**Comment by jorluos** [comment]
agregue un ghub actions para el verificar el estilo del codigo, para que sea igual cada uno de sus archivos

**Comment by samuelbonillaf** [comment]
En unos hay camel y en otros hay snake case

**Comment by samuelbonillaf** [comment]
Falto tambien otros estandares longitud de linea y espaciado pero F
