### ISSUE TITLE
Interfaz de usuario

### ISSUE THREAD

**Issue by Alejost7** [300CIS017-Object-Oriented-Programming/proyecto-3-pinche_trump#23]
## Tareas:
- Permitir que todo sea muy intuitivo para el usuario
- Que no sea aburrido para el usuario
- Tener bien implementada la comunicación y separación lógica-interfaz

**Comment by Alejost7** [comment]
Se ha terminado con éxito todos los detalles de la página principal. La primera página que recibirá al usuario está bien implementada, capta la atención del usuario y es bastante intuitiva

**Comment by jorluos** [comment]
muy buena pagina principal, me gusta el estilo :)

**Comment by samuelbonillaf** [comment]
Ya esta casi listo solo falta cambiar la imagen de stock que en homepage
