### ISSUE TITLE
Selección de Programas para Análisis

### ISSUE THREAD

**Issue by Alejost7** [300CIS017-Object-Oriented-Programming/proyecto-3-pinche_trump#8]
### Tareas:
- Añadir checkboxes a la tabla de resultados.
- Guardar las selecciones del usuario para su uso posterior en el análisis.

**Comment by samuelbonillaf** [comment]
No tuene checkboxes en el Analisis final
Se guardan pero después de ver una opción se reinician si retroceden para ver otra
