### ISSUE TITLE
Implementar Navegación en Pestañas 

### ISSUE THREAD

**Issue by Alejost7** [300CIS017-Object-Oriented-Programming/proyecto-3-pinche_trump#9]
### Tareas: 
- Crear pestañas en la interfaz de Streamlit.
- Organizar las funcionalidades en las pestañas correspondientes.
- Asegurar una navegación fácil y fluida entre las pestañas

**Comment by jorluos** [comment]
EN ALGUNAS PARTES DEL CODIGO YA ESTA IMPLEMENTADA ESTA PARTE, NO LA CIERRO PORQUE TODAVIA FALTA ALGO

**Comment by samuelbonillaf** [comment]
Ya esta listo funciona bien
